print("Student 1:")
print("Complete Name: Gwynette D. Galleros")
print("Course: Bachelor of Science in Computer Science")
print("Section: CS1D")
print("Age: 18 years old")
print("Birthday: October 3, 2004")
print("Complete Home Address: Purok 5, Poblacion, Kapatagan, Lanao Del Norte")
print("")
print("Student 2: ")
print("Complete Name: Alyssa Euana Luna")
print("Course: Bachelor of Science in Computer Science")
print("Section: CS1D")
print("Age: 20")
print("Birthday: May 29, 2003")
print("Complete Home Address: P 1, B 22, L 16, Villa Flora Subd., Cugman, Cagayan de Oro City")
